name: Release

on:
  workflow_call:
    inputs:
      tags:
        type: boolean
        required: false

jobs:
  release:
    # if: startsWith(github.ref, 'refs/tags/') # Unco
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: false

      # Download 
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of build files
        run: ls -R artifacts/**/*.*

      # Get latest tag
      - name: 'Get Previous tag'
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        # with:
        #   fallback: 1.0.0 
      
      # Release
      - name: Release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        with:
          files: |
            artifacts/**/*.zip
            artifacts/**/*.apk
          tag_name: ${{ steps.previoustag.outputs.tag }}
